import { Inter } from "next/font/google";
import "./globals.css";
import WalletContextProvider from "@/context/WalletContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WalletContextProvider>
          <div>
            {children}
          </div>
        </WalletContextProvider>
      </body>
    </html>
  );
}
