import { Inter } from "next/font/google";
import "./globals.css";
import WalletContextProvider from "@/context/WalletContext";
import PixelTrailCanvas from "@/components/Pixeltrail";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WalletContextProvider>
          <PixelTrailCanvas
            pixelSize={45}
            pixelColor="255, 0, 0"
            fadeSpeed={0.01}
            trailDuration={50}
          />
          <div style={{ position: 'relative', zIndex: 1 }}>
            {children}
          </div>
        </WalletContextProvider>
      </body>
    </html>
  );
}
